invenio_grobid/__init__.py
# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015, 2016 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

"""Invenio module to interact with Grobid API for metadata extraction."""

from __future__ import absolute_import, print_function

from .ext import InvenioGrobid
from .version import __version__

__all__ = ('__version__', 'InvenioGrobid')

invenio_grobid/views.py
# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015 CERN.
#
# Invenio is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

"""Define base Grobid Blueprint."""

from flask import Blueprint, abort, jsonify, redirect, render_template, request

from flask_login import login_required

from .api import process_pdf_stream, submit_record
from .errors import GrobidRequestError
from .mapping import tei_to_dict

blueprint = Blueprint('grobid', __name__, url_prefix="/grobid",
                      template_folder='templates',
                      static_folder='static')


@blueprint.route('/')
@blueprint.route('/index')
@login_required
def index():
    """Main entry point."""
    return render_template("grobid/index.html")


@blueprint.route('/upload', methods=["POST"])
@login_required
def process_file():
    """Send given file to Grobid for processing and return results."""
    uploaded_file = request.files['file']

    try:
        xml = process_pdf_stream(uploaded_file.stream)
    except GrobidRequestError:
        abort(500)

    return jsonify(**tei_to_dict(xml))


@blueprint.route('/submit', methods=["POST"])
@login_required
def submit():
    """Send metadata extracted by Grobid for further processing."""
    submitted_json = request.get_json()

    submit_record(submitted_json)

    return jsonify({'status': 'success'})

invenio_grobid/templates/grobid/base.html
{#
# This file is part of Invenio.
# Copyright (C) 2016 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.
#}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <script src="{{ url_for('static', filename='node_modules/almond/almond.js') }}"></script>
    {%- block css %}{%- endblock css %}
    {%- block javascript %}{%- endblock javascript %}
  </head>
  <body>
    {%- block page_header %}
    {%- endblock page_header %}
    {%- block page_body %}
    {%- endblock page_body %}
  </body>
</html>

invenio_grobid/templates/grobid/index.html
{#
# This file is part of Invenio.
# Copyright (C) 2015 CERN.
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation, Inc.,
# 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#}

{% extends config.GROBID_BASE_TEMPLATE %}


{%- block css %}
  {{ super() }}
  {%- assets "invenio_grobid_css" %}
    <link href="{{ ASSET_URL }}" rel="stylesheet">
  {%- endassets %}
{%- endblock css %}

{% block javascript %}
  {{ super() }}

  {% assets "invenio_grobid_js" %}
  <script src="{{ ASSET_URL }}"></script>
  {% endassets %}

  <script type="text/javascript">
    require(["js/grobid/grobid"],
      function(GROBID) {

      var grobid = GROBID.GROBID({});
    });
  </script>
{%- endblock javascript %}

{% block body %}
  <div class="container container-action">
    <div class="row">
      <div class="col-md-12">
        <h1 class="pull-left grobid-logo"><a href="{{url_for('grobid.index')}}">GROB<span>ID</span></a></h1>
        <form action="{{url_for('grobid.process_file')}}" method="post" enctype="multipart/form-data" class="form-inline pull-right grobid-form">
          <div class="form-group">
            <div class="input-group">
              <input type="text" class="form-control input-lg grobid-text" readonly/>
              <span class="input-group-btn">
                <span class="btn btn-warning btn-lg btn-file grobid-file">
                  Choose File <input type="file" name="file"/>
                </span>
              </span>
            </div>
          </div>
          <button type="submit" class="btn btn-lg btn-primary">Upload</button>
        </form>
      </div>
    </div>
  </div>

  <div class="container container-results">
    <dl class="dl-horizontal">
      <dt>Title</dt>
      <dd>The LCA Problem Revisited</dd>
      <dt>Authors</dt>
      <dd>
        <ul>
          <li>Michael A. Bender (SUNY Stony Brook)</li>
          <li>Martín Farach-Colton (Rutgers University)</li>
        </ul>
      </dd>
      <dt>Abstract</dt>
      <dd>We present a very simple algorithm for the Least Common Ancestor problem. We thus dispel the frequently held notion that an optimal LCA computation is unwieldy and unimplementable. Interestingly, this algorithm is a sequentialization of a previously known PRAM algorithm of Berkman, Breslauer, Galil, Schieber, and Vishkin.</dd>
      <dt>Keywords</dt>
      <dd>
        <ul>
          <li>Data Structures</li>
          <li>Least Common Ancestor (LCA)</li>
          <li>Range Minimum Query (RMQ)</li>
          <li>Cartesian Tree</li>
        </ul>
      </dd>
      <dt>References</dt>
      <dd>
        <ol>
          <li>O. Berkman, D. Breslauer, Z. Galil, B. Schieber, and U. Vishkin. Highly parallelizable problems. In <em>Proc. of the 21st Ann. ACM Symp on Theory of Computing</em>, pages 309-319, 1989.</li>
          <li>D. Harel and R. E. Tarjan. Fast algorithms for finding nearest common ancestors. <em>SIAM J. Comput.,</em>, 13(2):338-355, 1984.</li>
          <li>B. Schieber and U. Vishkin. On finding lowest common ancestors: Simplification and parallelization. <em>SIAM J. Comput.</em>, 17:1253-1262, 1988.</li>
        </ol>
      </dd>
    </dl>
  </div>

  <div class="container container-action">
    <div class="row">
      <div class="col-md-12">
        <button type="submit" class="btn btn-primary btn-lg pull-right grobid-submit">Submit</button>
      </div>
    </div>
  </div>
{% endblock %}